name: suneel_printer_admin
description: Admin app for Suneel Printer.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  firebase_storage: ^5.1.0
  firebase_messaging: ^8.0.0-dev.8
  firebase_crashlytics: ^0.2.3+1
  firebase_performance: ^0.4.2
  flutter_local_notifications: ^3.0.1+6
  flutter_image_compress: ^0.7.0
  responsive_framework: ^0.0.11
  flutter_colorpicker: ^0.3.4
  flutter_slidable: ^0.5.7
  carousel_slider: ^2.3.1
  empty_widget: ^0.0.1
  file_picker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
