name: suneel_printer_admin
description: Admin app for Suneel Printer.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.0
  firebase_messaging: ^9.0.0
  firebase_crashlytics: ^2.0.1
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_image_compress: ^1.0.0-nullsafety
  cached_network_image: ^3.0.0-nullsafety
  flutter_colorpicker: ^0.4.0-nullsafety.0
  flutter_slidable: ^0.6.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  empty_widget: ^0.0.1
  file_picker: ^3.0.0
  shimmer: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
