name: ecomm
description: An E-Commerce app.

publish_to: "none"
version: 1.5.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_crashlytics: ^3.4.9
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  razorpay_flutter: ^1.3.6
  flutter_slidable: ^3.0.1
  carousel_slider: ^4.1.1
  flare_flutter: ^3.0.2
  url_launcher: ^6.1.2
  empty_widget: ^0.0.5
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
