analyzer:

linter:
  rules:
    - prefer_const_constructors
    - always_declare_return_types
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - hash_and_equals
    - non_constant_identifier_names
    - package_api_docs
    - package_prefixed_library_names
    - sort_child_properties_last
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_statements
    - unsafe_html
