name: e_commerce
description: A E-Commerce app.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-44.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_crashlytics: ^2.8.1
  flutter_secure_storage: ^5.0.2
  flutter_native_splash: ^2.2.3
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  razorpay_flutter: ^1.3.0
  flutter_slidable: ^1.3.0
  carousel_slider: ^4.1.1
  flare_flutter: ^3.0.2
  url_launcher: ^6.1.2
  empty_widget: ^0.0.5
  photo_view: ^0.14.0
  shimmer: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
