name: ecomm_admin
description: An E-Commerce Admin app.

publish_to: "none"
version: 1.5.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.9
  flutter_local_notifications: ^16.3.0
  flutter_image_compress: ^2.1.0
  flutter_native_splash: ^2.2.3
  cached_network_image: ^3.2.1
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^3.0.1
  carousel_slider: ^4.1.1
  empty_widget: ^0.0.5
  file_picker: ^6.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
