name: suneel_printer
description: An E-Commerce & Ordering App.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_crashlytics: ^1.0.0
  flutter_secure_storage: ^4.1.0
  cached_network_image: ^3.0.0-nullsafety
  shared_preferences: ^2.0.5
  razorpay_flutter: ^1.2.2
  flutter_slidable: ^0.6.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  flare_flutter: ^3.0.0-nullsafety.1
  url_launcher: ^6.0.2
  empty_widget: ^0.0.1
  photo_view: ^0.11.1
  shimmer: ^2.0.0-nullsafety.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/ 
