// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEu7awrK56t0ylp3HmXm5pyTZYO3qq9zM',
    appId: '1:222520880472:android:a0bb92c8e0c150cf59892d',
    messagingSenderId: '222520880472',
    projectId: 'e-commerce37',
    storageBucket: 'e-commerce37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3qfytDFrCfjpactvcR-x4euEC31kS6v4',
    appId: '1:222520880472:ios:51610b9b5915871e59892d',
    messagingSenderId: '222520880472',
    projectId: 'e-commerce37',
    storageBucket: 'e-commerce37.appspot.com',
    iosClientId: '222520880472-cd0a0cqrraj78esb89nuckqpohg4r3g0.apps.googleusercontent.com',
    iosBundleId: 'com.solvrz.eCommerce',
  );
}
